/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pck;

import java.awt.Color;

/**
 *
 * @author tecna
 */
public class EmentaUser extends javax.swing.JFrame {
    int xx, yy;
    LoginFrame login;
    /**
     * Creates new form EmentaUser
     */
    public EmentaUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ementa_IEFPPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Ementa_IEFPPU").createEntityManager();
        ementaiefpQuery = java.beans.Beans.isDesignTime() ? null : Ementa_IEFPPUEntityManager.createQuery("SELECT e FROM Ementaiefp e");
        ementaiefpList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ementaiefpQuery.getResultList();
        ementaiefpQuery1 = java.beans.Beans.isDesignTime() ? null : Ementa_IEFPPUEntityManager.createQuery("SELECT e FROM Ementaiefp e");
        ementaiefpList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ementaiefpQuery1.getResultList();
        HeaderPanel2 = new javax.swing.JPanel();
        Setubal2 = new javax.swing.JLabel();
        IEFP2 = new javax.swing.JLabel();
        talheres2 = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        Ementa_Semana = new javax.swing.JLabel();
        IEFP_Logo = new javax.swing.JLabel();
        Ementa_Semana1 = new javax.swing.JLabel();
        lblExit2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 740));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        HeaderPanel2.setBackground(new java.awt.Color(0, 153, 51));
        HeaderPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderPanel2MouseDragged(evt);
            }
        });
        HeaderPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderPanel2MousePressed(evt);
            }
        });
        HeaderPanel2.setLayout(null);

        Setubal2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Setubal2.setForeground(new java.awt.Color(255, 255, 255));
        Setubal2.setText(" SETÚBAL");
        HeaderPanel2.add(Setubal2);
        Setubal2.setBounds(220, 10, 150, 50);

        IEFP2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        IEFP2.setForeground(new java.awt.Color(255, 255, 255));
        IEFP2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IEFP2.setText("IEFP ");
        HeaderPanel2.add(IEFP2);
        IEFP2.setBounds(140, 10, 80, 50);

        talheres2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        talheres2.setForeground(new java.awt.Color(255, 255, 255));
        talheres2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/icons/Restaurant_20px.png"))); // NOI18N
        HeaderPanel2.add(talheres2);
        talheres2.setBounds(170, 50, 20, 30);

        lblMinimize.setBackground(new java.awt.Color(0, 151, 53));
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/icons/Minimize Window_32px.png"))); // NOI18N
        lblMinimize.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        HeaderPanel2.add(lblMinimize);
        lblMinimize.setBounds(940, 0, 30, 30);

        Ementa_Semana.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Ementa_Semana.setForeground(new java.awt.Color(255, 255, 255));
        Ementa_Semana.setText("-  EMENTA SEMANAL ");
        HeaderPanel2.add(Ementa_Semana);
        Ementa_Semana.setBounds(190, 50, 180, 30);

        IEFP_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/icons/IEFP_branco_png_60px.png"))); // NOI18N
        HeaderPanel2.add(IEFP_Logo);
        IEFP_Logo.setBounds(60, 10, 80, 70);

        Ementa_Semana1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Ementa_Semana1.setForeground(new java.awt.Color(255, 255, 255));
        Ementa_Semana1.setText("User Mode");
        Ementa_Semana1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ementa_Semana1MouseClicked(evt);
            }
        });
        HeaderPanel2.add(Ementa_Semana1);
        Ementa_Semana1.setBounds(900, 70, 100, 30);

        lblExit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/icons/Close Window_32px.png"))); // NOI18N
        lblExit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit2MouseClicked(evt);
            }
        });
        HeaderPanel2.add(lblExit2);
        lblExit2.setBounds(970, 0, 30, 30);

        getContentPane().add(HeaderPanel2);
        HeaderPanel2.setBounds(0, 0, 1000, 100);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(530, 230, 340, 150);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:

        this.setState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        // TODO add your handling code here:
        lblMinimize.setBackground(new Color(0,120,40));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        // TODO add your handling code here:
        lblMinimize.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void Ementa_Semana1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ementa_Semana1MouseClicked
        // TODO add your handling code here:
        login = new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ementa_Semana1MouseClicked

    private void HeaderPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanel2MouseDragged
        // TODO add your handling code here:

        this.setLocation(evt.getXOnScreen()-xx,evt.getYOnScreen()-yy);
    }//GEN-LAST:event_HeaderPanel2MouseDragged

    private void HeaderPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanel2MousePressed
        // TODO add your handling code here:

        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_HeaderPanel2MousePressed

    private void lblExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit2MouseClicked
        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_lblExit2MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //New combo box
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmentaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmentaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmentaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmentaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmentaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager Ementa_IEFPPUEntityManager;
    private javax.swing.JLabel Ementa_Semana;
    private javax.swing.JLabel Ementa_Semana1;
    private javax.swing.JPanel HeaderPanel2;
    private javax.swing.JLabel IEFP2;
    private javax.swing.JLabel IEFP_Logo;
    private javax.swing.JLabel Setubal2;
    private java.util.List<pck.Ementaiefp> ementaiefpList;
    private java.util.List<pck.Ementaiefp> ementaiefpList1;
    private javax.persistence.Query ementaiefpQuery;
    private javax.persistence.Query ementaiefpQuery1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblExit2;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel talheres2;
    // End of variables declaration//GEN-END:variables
}
