/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pck;

import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author tecna
 */
public class EmentaAdminAdd extends JPanel {
    
    int xx, yy;
    EmentaAdmin admin;
    
    
    public EmentaAdminAdd() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Ementa_IEFPPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM Ementaiefp e");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        HeaderPanel = new javax.swing.JPanel();
        IEFP_Logo = new javax.swing.JLabel();
        Setubal = new javax.swing.JLabel();
        IEFP = new javax.swing.JLabel();
        talheres = new javax.swing.JLabel();
        lblAdm1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setMinimumSize(new java.awt.Dimension(658, 451));
        setPreferredSize(new java.awt.Dimension(658, 451));
        setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${diadasemana}"));
        columnBinding.setColumnName("Diadasemana");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idementa}"));
        columnBinding.setColumnName("Idementa");
        columnBinding.setColumnClass(Short.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${carne}"));
        columnBinding.setColumnName("Carne");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${peixe}"));
        columnBinding.setColumnName("Peixe");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dieta}"));
        columnBinding.setColumnName("Dieta");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${opcao}"));
        columnBinding.setColumnName("Opcao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${alternativa}"));
        columnBinding.setColumnName("Alternativa");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);

        masterScrollPane.setViewportView(masterTable);

        add(masterScrollPane);
        masterScrollPane.setBounds(10, 150, 630, 200);

        saveButton.setText("Guardar");
        saveButton.addActionListener(formListener);
        add(saveButton);
        saveButton.setBounds(340, 370, 160, 60);

        newButton.setText("Nova Ementa");
        newButton.addActionListener(formListener);
        add(newButton);
        newButton.setBounds(10, 370, 160, 60);

        deleteButton.setText("Apagar Linha");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);
        add(deleteButton);
        deleteButton.setBounds(190, 370, 130, 60);

        HeaderPanel.setBackground(new java.awt.Color(0, 153, 51));
        HeaderPanel.addMouseMotionListener(formListener);
        HeaderPanel.addMouseListener(formListener);
        HeaderPanel.setLayout(null);

        IEFP_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/icons/IEFP_branco_png.png"))); // NOI18N
        HeaderPanel.add(IEFP_Logo);
        IEFP_Logo.setBounds(30, 20, 110, 90);

        Setubal.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        Setubal.setForeground(new java.awt.Color(255, 255, 255));
        Setubal.setText(" SETÚBAL");
        HeaderPanel.add(Setubal);
        Setubal.setBounds(260, 20, 250, 50);

        IEFP.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        IEFP.setForeground(new java.awt.Color(255, 255, 255));
        IEFP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IEFP.setText("IEFP ");
        HeaderPanel.add(IEFP);
        IEFP.setBounds(130, 20, 150, 50);

        talheres.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        talheres.setForeground(new java.awt.Color(255, 255, 255));
        talheres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/icons/Restaurant_32px.png"))); // NOI18N
        HeaderPanel.add(talheres);
        talheres.setBounds(180, 70, 40, 30);

        lblAdm1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdm1.setForeground(new java.awt.Color(255, 255, 255));
        lblAdm1.setText("Adicionar Ementa");
        HeaderPanel.add(lblAdm1);
        lblAdm1.setBounds(280, 110, 130, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" EMENTA SEMANAL ");
        HeaderPanel.add(jLabel7);
        jLabel7.setBounds(220, 70, 300, 30);

        add(HeaderPanel);
        HeaderPanel.setBounds(0, 0, 660, 130);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(formListener);
        add(btnVoltar);
        btnVoltar.setBounds(523, 370, 120, 60);

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.MouseMotionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == saveButton) {
                EmentaAdminAdd.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                EmentaAdminAdd.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                EmentaAdminAdd.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == btnVoltar) {
                EmentaAdminAdd.this.btnVoltarActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == HeaderPanel) {
                EmentaAdminAdd.this.HeaderPanelMousePressed(evt);
            }
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == HeaderPanel) {
                EmentaAdminAdd.this.HeaderPanelMouseDragged(evt);
            }
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<pck.Ementaiefp> toRemove = new ArrayList<pck.Ementaiefp>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            pck.Ementaiefp e = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(e);
            entityManager.remove(e);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        pck.Ementaiefp e = new pck.Ementaiefp();
        entityManager.persist(e);
        list.add(e);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newButtonActionPerformed
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<pck.Ementaiefp> merged = new ArrayList<pck.Ementaiefp>(list.size());
            for (pck.Ementaiefp e : list) {
                merged.add(entityManager.merge(e));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void HeaderPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMouseDragged
        // TODO add your handling code here:

        this.setLocation(evt.getXOnScreen()-xx,evt.getYOnScreen()-yy);

    }//GEN-LAST:event_HeaderPanelMouseDragged

    private void HeaderPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMousePressed
        // TODO add your handling code here:

        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_HeaderPanelMousePressed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        admin = new EmentaAdmin();
        admin.setVisible(true);
        
        
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel IEFP;
    private javax.swing.JLabel IEFP_Logo;
    private javax.swing.JLabel Setubal;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton deleteButton;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAdm1;
    private java.util.List<pck.Ementaiefp> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton newButton;
    private javax.persistence.Query query;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel talheres;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmentaAdminAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmentaAdminAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmentaAdminAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmentaAdminAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new EmentaAdminAdd());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }

    private void setState(int ICONIFIED) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
