/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pck;

import java.awt.Color;
import java.util.Collection;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JDialog;

/**
 *
 * @author tecna
 */
public class EmentaAdmin extends javax.swing.JFrame {
    
    int xx, yy;
    LoginFrame login;
    EmentaAdminAdd ementa;
    EmentaUser user;
    
    public EmentaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Ementa_IEFPPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Ementa_IEFPPU").createEntityManager();
        ementaiefpQuery = java.beans.Beans.isDesignTime() ? null : Ementa_IEFPPUEntityManager.createQuery("SELECT e FROM Ementaiefp e");
        ementaiefpList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ementaiefpQuery.getResultList();
        HeaderPanel = new javax.swing.JPanel();
        Setubal = new javax.swing.JLabel();
        IEFP = new javax.swing.JLabel();
        talheres = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        Ementa_Semana = new javax.swing.JLabel();
        IEFP_Logo = new javax.swing.JLabel();
        Ementa_Semana1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmenta = new javax.swing.JTable();
        MenuPanel2 = new javax.swing.JPanel();
        btnAddEmenta = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JLabel();
        btnVerUser = new javax.swing.JLabel();
        btnApagarEmenta = new javax.swing.JLabel();
        btnEmentaMaster = new javax.swing.JLabel();
        lbltitleTab = new javax.swing.JLabel();
        txtAlternativa = new javax.swing.JTextField();
        txtDieta = new javax.swing.JTextField();
        txtPeixe = new javax.swing.JTextField();
        txtDiaDaSemana = new javax.swing.JTextField();
        txtOpcao = new javax.swing.JTextField();
        lbltitleTab1 = new javax.swing.JLabel();
        lbltitleTab2 = new javax.swing.JLabel();
        txtCarne = new javax.swing.JTextField();
        lbltitleTab3 = new javax.swing.JLabel();
        lbltitleTab4 = new javax.swing.JLabel();
        lbltitleTab5 = new javax.swing.JLabel();
        lbltitleTab6 = new javax.swing.JLabel();
        lbltitleTab7 = new javax.swing.JLabel();
        lbltitleTab8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lbltitleTab9 = new javax.swing.JLabel();
        txtPratos = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lbltitleTab11 = new javax.swing.JLabel();
        lbltitleTab12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 740));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 740));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        HeaderPanel.setBackground(new java.awt.Color(0, 153, 51));
        HeaderPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderPanelMouseDragged(evt);
            }
        });
        HeaderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderPanelMousePressed(evt);
            }
        });
        HeaderPanel.setLayout(null);

        Setubal.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Setubal.setForeground(new java.awt.Color(255, 255, 255));
        Setubal.setText(" SETÚBAL");
        HeaderPanel.add(Setubal);
        Setubal.setBounds(220, 10, 150, 50);

        IEFP.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        IEFP.setForeground(new java.awt.Color(255, 255, 255));
        IEFP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IEFP.setText("IEFP ");
        HeaderPanel.add(IEFP);
        IEFP.setBounds(140, 10, 80, 50);

        talheres.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        talheres.setForeground(new java.awt.Color(255, 255, 255));
        talheres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/icons/Restaurant_20px.png"))); // NOI18N
        HeaderPanel.add(talheres);
        talheres.setBounds(170, 50, 20, 30);

        lblExit.setBackground(new java.awt.Color(0, 151, 53));
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/icons/Close Window_32px.png"))); // NOI18N
        lblExit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        HeaderPanel.add(lblExit);
        lblExit.setBounds(970, 0, 30, 30);

        lblMinimize.setBackground(new java.awt.Color(0, 151, 53));
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/icons/Minimize Window_32px.png"))); // NOI18N
        lblMinimize.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        HeaderPanel.add(lblMinimize);
        lblMinimize.setBounds(940, 0, 30, 30);

        Ementa_Semana.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Ementa_Semana.setForeground(new java.awt.Color(255, 255, 255));
        Ementa_Semana.setText("-  EMENTA SEMANAL ");
        HeaderPanel.add(Ementa_Semana);
        Ementa_Semana.setBounds(190, 50, 180, 30);

        IEFP_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/icons/IEFP_branco_png_60px.png"))); // NOI18N
        HeaderPanel.add(IEFP_Logo);
        IEFP_Logo.setBounds(60, 10, 80, 70);

        Ementa_Semana1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Ementa_Semana1.setForeground(new java.awt.Color(255, 255, 255));
        Ementa_Semana1.setText("Admin Mode");
        Ementa_Semana1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ementa_Semana1MouseClicked(evt);
            }
        });
        HeaderPanel.add(Ementa_Semana1);
        Ementa_Semana1.setBounds(890, 70, 110, 30);

        getContentPane().add(HeaderPanel);
        HeaderPanel.setBounds(0, 0, 1000, 100);

        tableEmenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        tableEmenta.setOpaque(false);
        tableEmenta.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ementaiefpList, tableEmenta);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idementa}"));
        columnBinding.setColumnName("ID");
        columnBinding.setColumnClass(Short.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${diadasemana}"));
        columnBinding.setColumnName("Dia Semana");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${carne}"));
        columnBinding.setColumnName("Carne");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${peixe}"));
        columnBinding.setColumnName("Peixe");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${opcao}"));
        columnBinding.setColumnName("Opção");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dieta}"));
        columnBinding.setColumnName("Dieta");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${alternativa}"));
        columnBinding.setColumnName("Alternativa");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tableEmenta);
        if (tableEmenta.getColumnModel().getColumnCount() > 0) {
            tableEmenta.getColumnModel().getColumn(0).setResizable(false);
            tableEmenta.getColumnModel().getColumn(1).setResizable(false);
            tableEmenta.getColumnModel().getColumn(2).setResizable(false);
            tableEmenta.getColumnModel().getColumn(3).setResizable(false);
            tableEmenta.getColumnModel().getColumn(4).setResizable(false);
            tableEmenta.getColumnModel().getColumn(5).setResizable(false);
            tableEmenta.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 150, 770, 270);

        MenuPanel2.setBackground(new java.awt.Color(0, 185, 81));
        MenuPanel2.setLayout(null);

        btnAddEmenta.setBackground(new java.awt.Color(0, 185, 81));
        btnAddEmenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddEmenta.setForeground(new java.awt.Color(240, 240, 240));
        btnAddEmenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddEmenta.setText("Adicionar Ementa");
        btnAddEmenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddEmenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddEmenta.setOpaque(true);
        btnAddEmenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddEmentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddEmentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddEmentaMouseExited(evt);
            }
        });
        MenuPanel2.add(btnAddEmenta);
        btnAddEmenta.setBounds(0, 140, 180, 70);

        btnAtualizar.setBackground(new java.awt.Color(0, 185, 81));
        btnAtualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(240, 240, 240));
        btnAtualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAtualizar.setText("Atualizar Ementa");
        btnAtualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.setOpaque(true);
        btnAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseExited(evt);
            }
        });
        MenuPanel2.add(btnAtualizar);
        btnAtualizar.setBounds(0, 40, 180, 70);

        btnVerUser.setBackground(new java.awt.Color(0, 185, 81));
        btnVerUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVerUser.setForeground(new java.awt.Color(240, 240, 240));
        btnVerUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVerUser.setText("Ver como User");
        btnVerUser.setToolTipText("");
        btnVerUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerUser.setOpaque(true);
        btnVerUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerUserMouseExited(evt);
            }
        });
        MenuPanel2.add(btnVerUser);
        btnVerUser.setBounds(0, 440, 180, 70);

        btnApagarEmenta.setBackground(new java.awt.Color(0, 185, 81));
        btnApagarEmenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnApagarEmenta.setForeground(new java.awt.Color(240, 240, 240));
        btnApagarEmenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnApagarEmenta.setText("Apagar Ementa do Dia");
        btnApagarEmenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApagarEmenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApagarEmenta.setOpaque(true);
        btnApagarEmenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApagarEmentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApagarEmentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApagarEmentaMouseExited(evt);
            }
        });
        MenuPanel2.add(btnApagarEmenta);
        btnApagarEmenta.setBounds(0, 240, 180, 70);

        btnEmentaMaster.setBackground(new java.awt.Color(0, 185, 81));
        btnEmentaMaster.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEmentaMaster.setForeground(new java.awt.Color(240, 240, 240));
        btnEmentaMaster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEmentaMaster.setText("Ementa Master");
        btnEmentaMaster.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmentaMaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmentaMaster.setOpaque(true);
        btnEmentaMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmentaMasterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmentaMasterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmentaMasterMouseExited(evt);
            }
        });
        MenuPanel2.add(btnEmentaMaster);
        btnEmentaMaster.setBounds(0, 340, 180, 70);

        getContentPane().add(MenuPanel2);
        MenuPanel2.setBounds(0, 100, 180, 640);

        lbltitleTab.setBackground(new java.awt.Color(0, 204, 102));
        lbltitleTab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab.setText("Peixe");
        lbltitleTab.setOpaque(true);
        lbltitleTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTabMouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab);
        lbltitleTab.setBounds(210, 550, 120, 30);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableEmenta, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.alternativa}"), txtAlternativa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(txtAlternativa);
        txtAlternativa.setBounds(330, 700, 250, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableEmenta, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.dieta}"), txtDieta, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(txtDieta);
        txtDieta.setBounds(330, 600, 250, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableEmenta, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.peixe}"), txtPeixe, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(txtPeixe);
        txtPeixe.setBounds(330, 550, 250, 30);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableEmenta, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.diadasemana}"), txtDiaDaSemana, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(txtDiaDaSemana);
        txtDiaDaSemana.setBounds(800, 440, 180, 40);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableEmenta, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.opcao}"), txtOpcao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(txtOpcao);
        txtOpcao.setBounds(330, 650, 250, 30);

        lbltitleTab1.setBackground(new java.awt.Color(0, 185, 81));
        lbltitleTab1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab1.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab1.setText("Ementa");
        lbltitleTab1.setOpaque(true);
        lbltitleTab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab1MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab1);
        lbltitleTab1.setBounds(210, 110, 280, 40);

        lbltitleTab2.setBackground(new java.awt.Color(0, 185, 81));
        lbltitleTab2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab2.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab2.setText("Adicionar Ementa");
        lbltitleTab2.setOpaque(true);
        lbltitleTab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab2MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab2);
        lbltitleTab2.setBounds(210, 440, 370, 40);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableEmenta, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.carne}"), txtCarne, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(txtCarne);
        txtCarne.setBounds(330, 500, 250, 30);

        lbltitleTab3.setBackground(new java.awt.Color(0, 185, 81));
        lbltitleTab3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab3.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab3.setText("Dia Da Semana");
        lbltitleTab3.setOpaque(true);
        lbltitleTab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab3MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab3);
        lbltitleTab3.setBounds(610, 440, 190, 40);

        lbltitleTab4.setBackground(new java.awt.Color(0, 204, 102));
        lbltitleTab4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab4.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab4.setText("Dieta");
        lbltitleTab4.setOpaque(true);
        lbltitleTab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab4MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab4);
        lbltitleTab4.setBounds(210, 600, 120, 30);

        lbltitleTab5.setBackground(new java.awt.Color(0, 204, 102));
        lbltitleTab5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab5.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab5.setText("Opção");
        lbltitleTab5.setOpaque(true);
        lbltitleTab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab5MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab5);
        lbltitleTab5.setBounds(210, 650, 120, 30);

        lbltitleTab6.setBackground(new java.awt.Color(0, 204, 102));
        lbltitleTab6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab6.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab6.setText("Carne");
        lbltitleTab6.setOpaque(true);
        lbltitleTab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab6MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab6);
        lbltitleTab6.setBounds(210, 500, 120, 30);

        lbltitleTab7.setBackground(new java.awt.Color(0, 204, 102));
        lbltitleTab7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab7.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab7.setText("Alternativa");
        lbltitleTab7.setOpaque(true);
        lbltitleTab7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab7MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab7);
        lbltitleTab7.setBounds(210, 700, 120, 30);

        lbltitleTab8.setBackground(new java.awt.Color(0, 185, 81));
        lbltitleTab8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab8.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab8.setText("Pesq. Por Dia da Semana");
        lbltitleTab8.setOpaque(true);
        lbltitleTab8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab8MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab8);
        lbltitleTab8.setBounds(610, 590, 200, 40);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tableEmenta, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idementa}"), txtID, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(txtID);
        txtID.setBounds(800, 490, 180, 40);

        lbltitleTab9.setBackground(new java.awt.Color(0, 185, 81));
        lbltitleTab9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab9.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab9.setText("ID Ementa");
        lbltitleTab9.setOpaque(true);
        lbltitleTab9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab9MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab9);
        lbltitleTab9.setBounds(610, 490, 190, 40);

        txtPratos.setEnabled(false);
        getContentPane().add(txtPratos);
        txtPratos.setBounds(760, 640, 60, 40);

        btnPesquisa.setBackground(new java.awt.Color(0, 185, 81));
        btnPesquisa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPesquisa.setForeground(new java.awt.Color(240, 240, 240));
        btnPesquisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPesquisa.setText("Pesq");
        btnPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisa.setOpaque(true);
        btnPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisaMouseExited(evt);
            }
        });
        getContentPane().add(btnPesquisa);
        btnPesquisa.setBounds(910, 540, 70, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(760, 540, 140, 40);

        lbltitleTab11.setBackground(new java.awt.Color(0, 185, 81));
        lbltitleTab11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab11.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab11.setText("N.º Ementas");
        lbltitleTab11.setOpaque(true);
        lbltitleTab11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab11MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab11);
        lbltitleTab11.setBounds(610, 640, 150, 40);

        lbltitleTab12.setBackground(new java.awt.Color(0, 185, 81));
        lbltitleTab12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltitleTab12.setForeground(new java.awt.Color(240, 240, 240));
        lbltitleTab12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitleTab12.setText("Pesquisar Ementa ");
        lbltitleTab12.setOpaque(true);
        lbltitleTab12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltitleTab12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltitleTab12MouseExited(evt);
            }
        });
        getContentPane().add(lbltitleTab12);
        lbltitleTab12.setBounds(610, 540, 150, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(810, 590, 170, 40);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        lblExit.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        // TODO add your handling code here:
        lblExit.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:

        this.setState(LoginFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        // TODO add your handling code here:
        lblMinimize.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        // TODO add your handling code here:
        lblMinimize.setBackground(new Color(0,153,51));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void Ementa_Semana1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ementa_Semana1MouseClicked
        // TODO add your handling code here:
        login = new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ementa_Semana1MouseClicked

    private void HeaderPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMouseDragged
        // TODO add your handling code here:

        this.setLocation(evt.getXOnScreen()-xx,evt.getYOnScreen()-yy);
    }//GEN-LAST:event_HeaderPanelMouseDragged

    private void HeaderPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMousePressed
        // TODO add your handling code here:

        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_HeaderPanelMousePressed

    private void btnAtualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseEntered
        // TODO add your handling code here:
             btnAtualizar.setBackground(new Color(0,204,102));

    }//GEN-LAST:event_btnAtualizarMouseEntered

    private void btnAddEmentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddEmentaMouseEntered
        // TODO add your handling code here:
          btnAddEmenta.setBackground(new Color(0,204,102));

    }//GEN-LAST:event_btnAddEmentaMouseEntered

    private void btnAtualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseExited
        // TODO add your handling code here:
        btnAtualizar.setBackground(new Color(0,185,81));

    }//GEN-LAST:event_btnAtualizarMouseExited

    private void btnVerUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerUserMouseClicked
        // TODO add your handling code here:
        user = new EmentaUser();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerUserMouseClicked

    private void btnEmentaMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmentaMasterMouseClicked
        // TODO add your handling code here:
        EmentaAdminAdd e = new EmentaAdminAdd();
        JDialog dialog = new JDialog(this, "awqeqw", true);
        dialog.add(e);
        dialog.pack();
        this.dispose();
        dialog.setVisible(true);
        
        //dialog.setUndecorated(true);
        //this.dispose();
    }//GEN-LAST:event_btnEmentaMasterMouseClicked

    private void btnApagarEmentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApagarEmentaMouseEntered
        // TODO add your handling code here:
        btnApagarEmenta.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btnApagarEmentaMouseEntered

    private void lbltitleTabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTabMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTabMouseEntered

    private void lbltitleTabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTabMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbltitleTabMouseExited

    private void btnVerUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerUserMouseEntered
        // TODO add your handling code here:
        btnVerUser.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btnVerUserMouseEntered

    private void btnAddEmentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddEmentaMouseExited
        // TODO add your handling code here:
        btnAddEmenta.setBackground(new Color(0,185,81));
    }//GEN-LAST:event_btnAddEmentaMouseExited

    private void btnApagarEmentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApagarEmentaMouseExited
        // TODO add your handling code here:
        btnApagarEmenta.setBackground(new Color(0,185,81));

    }//GEN-LAST:event_btnApagarEmentaMouseExited

    private void btnEmentaMasterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmentaMasterMouseExited
        // TODO add your handling code here:
                btnEmentaMaster.setBackground(new Color(0,185,81));

    }//GEN-LAST:event_btnEmentaMasterMouseExited

    private void btnEmentaMasterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmentaMasterMouseEntered
        // TODO add your handling code here:
        btnEmentaMaster.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btnEmentaMasterMouseEntered

    private void btnVerUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerUserMouseExited
        // TODO add your handling code here:
        btnVerUser.setBackground(new Color(0,185,81));
    }//GEN-LAST:event_btnVerUserMouseExited

    private void btnAddEmentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddEmentaMouseClicked
        // TODO add your handling code here:
        String carne, peixe, dieta, opcao, alternativa, diaDaSemana;
        short id;
        Ementaiefp data = new Ementaiefp();
        carne = txtCarne.getText();
        peixe = txtPeixe.getText();
        dieta = txtDieta.getText();
        opcao = txtOpcao.getText();
        id = Short.valueOf(txtID.getText());
        alternativa = txtAlternativa.getText();
        diaDaSemana = txtDiaDaSemana.getText();
        data.setIdementa(id);
        data.setCarne(carne);
        data.setAlternativa(alternativa);
        data.setPeixe(peixe);
        data.setOpcao(opcao);
        data.setDieta(dieta);
        data.setDiadasemana(diaDaSemana);
     
        Ementa_IEFPPUEntityManager.getTransaction().begin();
        Ementa_IEFPPUEntityManager.merge(data);
        Ementa_IEFPPUEntityManager.getTransaction().commit();
        
        
    }//GEN-LAST:event_btnAddEmentaMouseClicked

    private void btnAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseClicked
        // TODO add your handling code here:
        String carne, peixe, dieta, opcao, alternativa, diaDaSemana;
        short id;
        Ementaiefp data = new Ementaiefp();
        Ementa_IEFPPUEntityManager.getTransaction().begin();
        carne = txtCarne.getText();
        peixe = txtPeixe.getText();
        dieta = txtDieta.getText();
        opcao = txtOpcao.getText();
        id = Short.valueOf(txtID.getText());
        alternativa = txtAlternativa.getText();
        diaDaSemana = txtDiaDaSemana.getText();
        data.setIdementa(id);
        data.setCarne(carne);
        data.setAlternativa(alternativa);
        data.setPeixe(peixe);
        data.setOpcao(opcao);
        data.setDieta(dieta);
        data.setDiadasemana(diaDaSemana);
     
        Ementa_IEFPPUEntityManager.merge(data);
        Ementa_IEFPPUEntityManager.getTransaction().commit();
        
       
    }//GEN-LAST:event_btnAtualizarMouseClicked

    private void lbltitleTab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab1MouseEntered

    private void lbltitleTab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab1MouseExited

    private void lbltitleTab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab2MouseEntered

    private void lbltitleTab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab2MouseExited

    private void lbltitleTab3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab3MouseEntered

    private void lbltitleTab3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab3MouseExited

    private void lbltitleTab4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab4MouseEntered

    private void lbltitleTab4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab4MouseExited

    private void lbltitleTab5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab5MouseEntered

    private void lbltitleTab5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab5MouseExited

    private void lbltitleTab6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab6MouseEntered

    private void lbltitleTab6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab6MouseExited

    private void lbltitleTab7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab7MouseEntered

    private void lbltitleTab7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab7MouseExited

    private void lbltitleTab8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab8MouseEntered

    private void lbltitleTab8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab8MouseExited

    private void btnApagarEmentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApagarEmentaMouseClicked
        // TODO add your handling code here:
        EntityManagerFactory factory = Persistence.createEntityManagerFactory("EMENTADBPU");
        EmentaiefpJpaController data2 = new EmentaiefpJpaController(factory);
        int row = tableEmenta.getSelectedRow();
        int col=0;
        
        long id = Long.valueOf(tableEmenta.getValueAt(row, col).toString());

        Query qr = Ementa_IEFPPUEntityManager.createNamedQuery("EmentaIEFP.findAll");
        
        Collection data = qr.getResultList();
        tableEmenta.clearSelection();
        //tableEmenta.addAll(data);
        tableEmenta.updateUI();
    }//GEN-LAST:event_btnApagarEmentaMouseClicked

    private void lbltitleTab9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab9MouseEntered

    private void lbltitleTab9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab9MouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        txtPratos.setText(String.valueOf(tableEmenta.getRowCount()));
        
    }//GEN-LAST:event_formComponentShown

    private void btnPesquisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaMouseEntered

    private void btnPesquisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaMouseExited

    private void lbltitleTab11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab11MouseEntered

    private void lbltitleTab11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab11MouseExited

    private void lbltitleTab12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab12MouseEntered

    private void lbltitleTab12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleTab12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitleTab12MouseExited

    private void btnPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaMouseClicked
        // TODO add your handling code here:
         Query qr = Ementa_IEFPPUEntityManager.createNamedQuery("EmentaIEFP.findByLoc"); 
    }//GEN-LAST:event_btnPesquisaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmentaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager Ementa_IEFPPUEntityManager;
    private javax.swing.JLabel Ementa_Semana;
    private javax.swing.JLabel Ementa_Semana1;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel IEFP;
    private javax.swing.JLabel IEFP_Logo;
    private javax.swing.JPanel MenuPanel2;
    private javax.swing.JLabel Setubal;
    private javax.swing.JLabel btnAddEmenta;
    private javax.swing.JLabel btnApagarEmenta;
    private javax.swing.JLabel btnAtualizar;
    private javax.swing.JLabel btnEmentaMaster;
    private javax.swing.JLabel btnPesquisa;
    private javax.swing.JLabel btnVerUser;
    private java.util.List<pck.Ementaiefp> ementaiefpList;
    private javax.persistence.Query ementaiefpQuery;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lbltitleTab;
    private javax.swing.JLabel lbltitleTab1;
    private javax.swing.JLabel lbltitleTab11;
    private javax.swing.JLabel lbltitleTab12;
    private javax.swing.JLabel lbltitleTab2;
    private javax.swing.JLabel lbltitleTab3;
    private javax.swing.JLabel lbltitleTab4;
    private javax.swing.JLabel lbltitleTab5;
    private javax.swing.JLabel lbltitleTab6;
    private javax.swing.JLabel lbltitleTab7;
    private javax.swing.JLabel lbltitleTab8;
    private javax.swing.JLabel lbltitleTab9;
    private javax.swing.JTable tableEmenta;
    private javax.swing.JLabel talheres;
    private javax.swing.JTextField txtAlternativa;
    private javax.swing.JTextField txtCarne;
    private javax.swing.JTextField txtDiaDaSemana;
    private javax.swing.JTextField txtDieta;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtOpcao;
    private javax.swing.JTextField txtPeixe;
    private javax.swing.JTextField txtPratos;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
